version: '3.8'

services:
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: rowan
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: ads_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"

  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --reload
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      REDIS_BROKER_URL: "redis://redis:6379/0"
      DATABASE_URL: "postgresql://user:password@db:5432/ads_db"

  worker:
    build: .
    command: celery -A app.tasks worker --loglevel=info
    volumes:
      - ./app:/app
    depends_on:
      - redis
      - db
    environment:
      REDIS_BROKER_URL: "redis://redis:6379/0"
      DATABASE_URL: "postgresql://user:password@db:5432/ads_db"

volumes:
  postgres_data:
